name: Build

# Run on every release created
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        with:
          token: ${{ secrets.GITHUB_REPO_ACCESS_TOKEN }}`

      - name: Install platform
        run: |
          arduino-cli core install IRNAS:stm32l0 --additional-urls "https://irnas.github.io/ArduinoCore-stm32l0/package_stm32l0_boards_index.json"
          arduino-cli lib update-index
          arduino-cli lib install "Adafruit ADS1X15"
          
      - name: Rename folder to main to keep arduino-cli happy
        run: mv src main
      
      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build for various board configurations
        run: python release.py v0.0
        
      - name: List files
        run: ls -R build/
