name: Build and release upon release created

# Run on every release created
on:
  release:
    types:
      - created
  workflow_dispatch:
  push:

jobs:
  release:
    name: Build process
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        with:
          token: ${{ secrets.GITHUB_REPO_ACCESS_TOKEN }}`

      - name: Install platform
        run: |
          arduino-cli core install IRNAS:stm32l0 --additional-urls "https://irnas.github.io/ArduinoCore-stm32l0/package_stm32l0_boards_index.json"
          arduino-cli lib update-index
          arduino-cli lib install "Adafruit ADS1X15"
          
      - name: Rename folder to main to keep arduino-cli happy
        run: mv src main
      
      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi

      - name: Install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build for various board configurations
        run: python release.py ${{ github.event.release.tag_name }}
        
      - name: List files
        run: ls -R build/

      - name: ZIP files
        uses: papeloto/action-zip@v1
        with:
          files: ./build/smartparks-rhino-tracker-firmware*
          dest: ./build/smartparks-rhino-tracker-firmware-${{ github.event.release.tag_name }}.zip

      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/
          asset_name: smartparks-rhino-tracker-firmware-${{ github.event.release.tag_name }}.zip
          asset_content_type: binary/octet-stream
